### ISSUE TITLE
对于Action运行失败后续解决方案的探讨🧠

### ISSUE THREAD

**Issue by lifeilin0421** [YooKing/HAUT_autoCheck#43]
Run python3 main.py <<EOF
开始尝试为用户0421打卡
<class 'requests.exceptions.ConnectionError'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f43fd0d5c10>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server.17wanxiao.com', port=443): Max retries exceeded with url: /campus/cam_iface46/exchangeSecretkey.action (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43fd0d5c10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in main
    campus = CampusCard(phone[index], password[index])
  File "/home/runner/work/HAUT_autoCheck/HAUT_autoCheck/campus/campus.py", line 25, in __init__
    self.exchange_secret()
  File "/home/runner/work/HAUT_autoCheck/HAUT_autoCheck/campus/campus.py", line 66, in exchange_secret
    verify=False
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='server.17wanxiao.com', port=443): Max retries exceeded with url: /campus/cam_iface46/exchangeSecretkey.action (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43fd0d5c10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 222, in <module>
    main()
  File "main.py", line 61, in main
    result=response
UnboundLocalError: local variable 'response' referenced before assignment
Error: Process completed with exit code 1.

**Comment by iskyil** [comment]
推荐下载本地Python运行，可能是github服务器问题

**Comment by peterpei1186861238** [comment]
大规模的打不上卡也许是人家后台发现同一ip段(还是海外)打了太多卡。
看错误是模拟登录就出错了，貌似是公钥交换的问题？

**Comment by P-PPPP** [comment]
大规模的打不上卡说不定是人家后台发现同一ip段(还是海外)打了太多卡。🤣
看错误是模拟登录就出错了，貌似是公钥交换的问题？

**Comment by lifeilin0421** [comment]
> 推荐下载本地Python运行，可能是github服务器问题

好的，我试试，谢谢。

**Comment by lifeilin0421** [comment]
> 大规模的打不上卡说不定是人家后台发现同一ip段(还是海外)打了太多卡。🤣
> 看错误是模拟登录就出错了，貌似是公钥交换的问题？

😂；😂

**Comment by zhazhalaila** [comment]
亲测，本地直接运行main.py有效

**Comment by lifeilin0421** [comment]
> 亲测，本地直接运行main.py有效

你好，怎样进行本地运行呢？

**Comment by zhazhalaila** [comment]
> > 亲测，本地直接运行main.py有效
> 
> 你好，怎样进行本地运行呢？

1. 下载依赖包
```
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
```
2. 修改main.py
    1. 在第10行填入手机号，密码，Server酱(填写格式为字符串)
    ```
   phone, password, sckey = ['xxx','xxx'], ['xxx','xxx'], ['xxx']
    ```
    2. 注释掉12-20行
3. 运行
```
python main.py
```

**Comment by P-PPPP** [comment]
如果是网络问题的话转战阿里云或者腾讯云的函数计算应该可行

**Comment by lifeilin0421** [comment]
> > > 亲测，本地直接运行main.py有效
> > 
> > 
> > 你好，怎样进行本地运行呢？
> 
> 1. 下载依赖包
> 
> ```
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
> ```
> 
> 1. 修改main.py
>    
>    1. 在第10行填入手机号，密码，Server酱(填写格式为字符串)
>    
>    ```
>    phone, password, sckey = ['xxx','xxx'], ['xxx','xxx'], ['xxx']
>    ```
>    
>    
>    
>    1. 注释掉12-20行
> 2. 运行
> 
> ```
> python main.py
> ```

好的，谢谢大佬。

**Comment by Revincx** [comment]
腾讯云函数版本初步测试通过
详见https://github.com/Revincx/HAUT_autoCheck_SCF

**Comment by lifeilin0421** [comment]
> 腾讯云函数版本初步测试通过
> 详见https://github.com/Revincx/HAUT_autoCheck_SCF

感谢大佬，尝试一下。

**Comment by YooKing** [comment]
### 部署到Linux服务器

1. 下载本项目
```
git clone https://github.com/YooKing/HAUT_autoCheck.git
```
2. 进入本项目目录
```
cd HAUT_autoCheck
```
3. 安装依赖包
```
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
```
4. 修改main.py  
    
    1. 在第10行填入手机号，密码，Server酱(填写格式为字符串)
    ```
   phone, password, sckey = ['xxx','xxx'], ['xxx','xxx'], ['xxx']
    ```
    2. 注释掉12-20行
5. 测试运行
    1. 在项目目录下终端中输入
    ```
    python3 main.py
    ```  

    2. 在英文环境可能出现错误，需要在出现中文的py文件首行加入
    ```
    # -*- coding: utf-8 -*- 
    ```
6. 定时运行

    1. 在终端输入
    ```
    crontab -e
    ```
    
    2. 在打开的文件里加入一行代码，这里的目录因人所异，表示每天八点半执行`python3 main.py`命令
    ```
    30 8 * * *  python3 /root/HAUT_autoCheck/main.py
    ```

**Comment by chillsoul** [comment]
可能是封了IP区域

**Comment by zhazhalaila** [comment]
总结一下使用crontab的注意事项

1. 若要查看crontab是否执行该命令，可以查看log文件，这样方便排查错误（服务器环境为CentOS7)
```
cat /var/log/cron
```
2. 注意时区，若为国内服务器，用的是国内时间，若为国外服务器，需要进行时间转换，可以在服务器键入`date`查看时区(我的是国内服务器，因此不需要转换时间）
```
[up@server up]# date
Sat Jan 16 18:06:11 CST 2021
```
3. 代码的print输出结果或者错误运行结果可以重定向给另一个文件，方便检查错误
```
30 8 * * *  python3 /root/HAUT_autoCheck/main.py > /root/HAUT_autoCheck/listener.log 2>&1
```
可以查看listener.log文件检查错误
```
cat /root/HAUT_autoCheck/listener.log
```

**Comment by Revincx** [comment]
> 总结一下使用crontab的注意事项
> 
> 1. 若要查看crontab是否执行该命令，可以查看log文件，这样方便排查错误（服务器环境为CentOS7)
> 
> ```
> cat /var/log/cron
> ```
> 
> 1. 注意时区，若为国内服务器，用的是国内时间，若为国外服务器，需要进行时间转换，可以在服务器键入`date`查看时区(我的是国内服务器，因此不需要转换时间）
> 
> ```
> [up@server up]# date
> Sat Jan 16 18:06:11 CST 2021
> ```
> 
> 1. 代码的print输出结果或者错误运行结果可以重定向给另一个文件，方便检查错误
> 
> ```
> 30 8 * * *  python3 /root/HAUT_autoCheck/main.py > /root/HAUT_autoCheck/listener.log 2>&1
> ```
> 
> 可以查看listener.log文件检查错误
> 
> ```
> cat /root/HAUT_autoCheck/listener.log
> ```

总结的可以，不过目前海外的服务器貌似被完美校园屏蔽

**Comment by zhazhalaila** [comment]
> > 总结一下使用crontab的注意事项
> > 
> > 1. 若要查看crontab是否执行该命令，可以查看log文件，这样方便排查错误（服务器环境为CentOS7)
> > 
> > ```
> > cat /var/log/cron
> > ```
> > 
> > 
> > 
> > 1. 注意时区，若为国内服务器，用的是国内时间，若为国外服务器，需要进行时间转换，可以在服务器键入`date`查看时区(我的是国内服务器，因此不需要转换时间）
> > 
> > ```
> > [up@server up]# date
> > Sat Jan 16 18:06:11 CST 2021
> > ```
> > 
> > 
> > 
> > 1. 代码的print输出结果或者错误运行结果可以重定向给另一个文件，方便检查错误
> > 
> > ```
> > 30 8 * * *  python3 /root/HAUT_autoCheck/main.py > /root/HAUT_autoCheck/listener.log 2>&1
> > ```
> > 
> > 
> > 可以查看listener.log文件检查错误
> > ```
> > cat /root/HAUT_autoCheck/listener.log
> > ```
> 
> 总结的可以，不过目前海外的服务器貌似被完美校园屏蔽

哈哈，那可以自动忽略第二条了

**Comment by zhazhalaila** [comment]
在服务器端同时装有Python2和Python3时安装包时需注意Python版本区别，`pip`对应Python2版本，`pip3`对应Python3版本
