### ISSUE TITLE
打卡出现问题

### ISSUE THREAD

**Issue by zhazhalaila** [YooKing/HAUT_autoCheck#50]
是IP被封了吗？
服务器没有打卡成功
```
<class 'KeyError'>
Traceback (most recent call last):
  File "main.py", line 31, in main
    userInfo=getUserInfo(token)
  File "main.py", line 88, in getUserInfo
    return response.json()['userInfo']
KeyError: 'userInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 223, in <module>
    main()
  File "main.py", line 62, in main
    result=response
UnboundLocalError: local variable 'response' referenced before assignment
```
在本地成功打卡一次后，再次打卡时又出现上述问题。

**Comment by zombie12138** [comment]
我看了一下感觉应该是登陆出问题了，而且那个登陆的项目已经删了😅

**Comment by zhazhalaila** [comment]
> 我看了一下感觉应该是登陆出问题了，而且那个登陆的项目已经删了😅

模拟登录的应该没问题，我本地成功打卡了一次，再次运行时候就不行了

**Comment by du1370484311** [comment]
我也是这个问题，前几天还好好的，现在就是这个userInfo=getUserInfo(token)报错
